server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/forumhub_db
    username: root
    password: TU_PASSWORD_AQUI
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 20
      minimum-idle: 5
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-timeout: 30000

  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

cors:
  allowed-origins:
    - http://localhost:3000
    - https://frontend-forumhub.com

# 🔑 Aquí definimos tu secreto JWT seguro
JWT_SECRET: "D#9fKpZ7!qRtX1wLm$3yN2vB8@hTjU5o"

logging:
  level:
    com.alura.forum.forumHub: DEBUG
